### ISSUE TITLE
Drawing logo

### ISSUE THREAD

**Issue by Rainbow7light** [dryotta/AvocadoBots2019#11]

**Comment by g2qin** [comment]
![image](https://user-images.githubusercontent.com/45957440/65396100-72d58580-dd57-11e9-97c9-959dd593c15f.png)

**Comment by g2qin** [comment]
![image](https://user-images.githubusercontent.com/45957440/65396106-87198280-dd57-11e9-9f85-99ee2b760098.png)
now i better

**Comment by g2qin** [comment]
![image](https://user-images.githubusercontent.com/45957440/65396107-95679e80-dd57-11e9-831b-50778f90df02.png)
NOW IT BETTER

**Comment by jennifer-m-gao** [comment]
Is it done yet?

**Comment by Rainbow7light** [comment]
It sucks

**Comment by g2qin** [comment]
![image](https://user-images.githubusercontent.com/45957440/65396112-a9130500-dd57-11e9-8733-fec0de570d5f.png)
ok NOW it better

**Comment by ellasu2009** [comment]
Is it just a circle?

**Comment by SuperMonkeyAZ** [comment]
Trash

**Comment by Rainbow7light** [comment]
Where r the Avocados

**Comment by qiangli2009** [comment]
no

**Comment by jennifer-m-gao** [comment]
Looks like it

**Comment by SuperMonkeyAZ** [comment]
staaaaaaaap

**Comment by qiangli2009** [comment]
cool

**Comment by qiangli2009** [comment]
nice

**Comment by jennifer-m-gao** [comment]
It looks like a sun in the night

**Comment by g2qin** [comment]
![thing this](https://user-images.githubusercontent.com/45957440/65396126-cfd13b80-dd57-11e9-9ebd-09a177f18584.png)
NOW IT WORK HAHA I VICTORY

**Comment by elainecchen** [comment]
What is it a circle?

**Comment by ghost** [comment]
Finally

**Comment by ellasu2009** [comment]
It still looks just like a circle.

**Comment by ghost** [comment]
OOOOOOOOOOOOOOOOH

**Comment by qiangli2009** [comment]
cool!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ellasu2009** [comment]
They look weird.

**Comment by jennifer-m-gao** [comment]
I didn't draw mine that fat

**Comment by ghost** [comment]
yeah you did

**Comment by g2qin** [comment]
jennifer fat so ye

**Comment by g2qin** [comment]
![le better](https://user-images.githubusercontent.com/45957440/65396173-61d94400-dd58-11e9-8576-147317b2eb94.png)
le better

**Comment by jennifer-m-gao** [comment]
thanks

**Comment by ghost** [comment]
Lmao

**Comment by g2qin** [comment]
yOur weLcOME

**Comment by SuperMonkeyAZ** [comment]
NO ONE CARES

**Comment by g2qin** [comment]
Lopado­temacho­selacho­galeo­kranio­leipsano­drim­hypo­trimmato­silphio­parao­melito­katakechy­meno­kichl­epi­kossypho­phatto­perister­alektryon­opte­kephallio­kigklo­peleio­lagoio­siraio­baphe­tragano­pterygon is the longest word in the dictonary

**Comment by dryotta** [comment]
https://user-images.githubusercontent.com/45957440/65396231-0e1b2a80-dd59-11e9-87ee-8482fffd9961.png

**Comment by dryotta** [comment]
![image](https://user-images.githubusercontent.com/31458253/65438382-3eef7400-ddda-11e9-9cf2-6b8b191dbfc3.png)

**Comment by g2qin** [comment]
HEEEEEYYY

**Comment by g2qin** [comment]
![eeeeeeemeeeee](https://user-images.githubusercontent.com/45957440/65472150-e98d8400-de26-11e9-8172-0dbf073bf027.png)
THE GRAY LOOK WEIRD

**Comment by g2qin** [comment]
suggestions??
**I SAID SUGGESTIONS**
_I SAID **SUGGESTIONS**_

**Comment by g2qin** [comment]
![asdasdasd](https://user-images.githubusercontent.com/45957440/65472711-ac76c100-de29-11e9-9fb4-ff07d420f92a.png)
MEEN

**Comment by jennifer-m-gao** [comment]
What does lopado­temacho­selacho­galeo­kranio­leipsano­drim­hypo­trimmato­silphio­parao­melito­katakechy­meno­kichl­epi­kossypho­phatto­perister­alektryon­opte­kephallio­kigklo­peleio­lagoio­siraio­baphe­tragano­pterygon mean?

**Comment by ellasu2009** [comment]
You should change the font of AVOCADOBOTS, also some islands are empty but I don't think that matters to much. Also, the sun blends in kind of wierdly. By the way, I don't know what that means.

**Comment by SuperMonkeyAZ** [comment]
Its a type of cancer
I think its breast cancer, not sure

**Comment by elainecchen** [comment]
It looks pretty nice.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
